### ISSUE TITLE
Netherlands Tax Rates

### ISSUE THREAD

**Issue by useraccount** [paulmillr/mnp#13]
If only Dutch taxes were as low as your tool suggests!

The lowest two tax bands in your tool fail to take into account the national insurance contributions (which are **mandatory for everyone**, be they employed or self-employed).

So instead of the first two brackets being 5.85% and 10.85% respectively, they're actually: 36.5% and 42% (as of 2015).

**Comment by paulmillr** [comment]
You're correct. Unfortunately we only include income taxes for now. I'll leave this open.
