### ISSUE TITLE
Add New Zealand

### ISSUE THREAD

**Issue by diegoteliz** [paulmillr/mnp#15]
Nice project @paulmillr @goshakkk, well done!

What do you think about adding *New Zealand* to the list?

I moved here a year ago and it was definitely the best decision. 

Here some reasons to include it on the list:

- [1st place on "Starting a Business"](http://www.doingbusiness.org/rankings)
- [2nd place on "Ease of Doing Business Rank"](http://www.doingbusiness.org/rankings)
- [1st place on countries with less corruption] (http://www.transparency.org/cpi2013/results/)
- [Low crime index](http://www.numbeo.com/crime/rankings_by_country.jsp)
- Mixed weather across the country
- Main language is English
- Wide range of cultures, languages and food (especially in Auckland)
- Some of the most beautiful places on earth

  - [Milford Sound](http://wallpapercave.com/wp/xZn6LHl.jpg)
  - [Cathedral Cove](http://browdiva.com/wp-content/uploads/2015/02/banner.jpg)
  - [Queenstown](http://s1.1zoom.net/big3/411/374700-svetik.jpg)
  - [Waitomo Caves](http://www.customdaytours.co.nz/wp-content/uploads/2015/09/caves.jpg)

- [Wide range of visas](https://www.immigration.govt.nz/new-zealand-visas) (Very easy for developers due to high demand (no diploma needed))
- [It's the land of The Hobbit!](http://www.hobbitontours.com/)
 
I think this country can't miss in the list.
If you want me to add it just let me know and I can contribute.

Cheers!

**Comment by paulmillr** [comment]
Yes, go ahead please. We would appreciate the contribution!

**Comment by diegoteliz** [comment]
Ok! [here](https://github.com/paulmillr/mnp/pull/16) it's the PR.
