### ISSUE TITLE
looking for cold climate countries

### ISSUE THREAD

**Issue by computingfreak** [paulmillr/mnp#19]
it's so strange that only Singapore is marked with a "Warm climate".
Besides the data seems to be static and not updated since 2014.
Perhaps one could use data from weatherspark.com.

**Comment by paulmillr** [comment]
yeah, you're free to update it

**Comment by paulmillr** [comment]
https://github.com/paulmillr/mnp/tree/gh-pages/source/app/countries
https://github.com/paulmillr/mnp/blob/gh-pages/source/app/components.js#L13
