### ISSUE TITLE
germany

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/mnp#9]
@goshakkk 

Any proofs that a person is able to work in Germany w/o the diploma?

**Comment by computingfreak** [comment]
https://www.reddit.com/r/germany/comments/7j7btp/work_permit_without_degree_for_noneu_citizen/

**Comment by computingfreak** [comment]
https://expatriates.stackexchange.com/questions/7079/is-it-true-that-you-dont-need-a-degree-to-work-as-an-it-specialist-in-germany
